version: '3'
services:
  customer-person-service:
    build:
      context: ./customer-person-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/banking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db

  transaction-account-service:
    build:
      context: ./transaction-account-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/banking
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db

  db:
    image: mysql:8.0 # Usamos la versión 8.0 de MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=banking
    ports:
      - "3306:3306"