services:
  # Customer Person Service
  customer-person-service:
    build:
      context: ./customer-person/customer-person
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db1:3308/customer_person
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      - db1
      - kafka
  
  # MySQL Database
  db1:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=customer_person
    ports:
      - "3308:3306"

  # Transaction Account Service
  transaction-account-service:
    build:
      context: ./transaction-account/transaction-account
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db2:3307/transaction_account
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
    depends_on:
      - db2
      - kafka

  # MySQL Database
  db2:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=transaction_account
    ports:
      - "3307:3306"

  # Zookeeper
  zookeeper:
    image: zookeeper:3.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE://0.0.0.0:9093
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_LISTENER_EXTERNAL: EXTERNAL://0.0.0.0:9092
    ports:
      - "9092:9092"  # Externally exposed port for external connections
      - "9093:9093"

# API Gateway
  api-gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - customer-person-service
      - transaction-account-service

  # Config Server
  config-server:
    build:
      context: ./config
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
  # Eureka Server
  eureka-server:
    build:
      context: ./gateway
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=eureka-server
      - eureka.client.fetch-registry=false
      - eureka.client.register-with-eureka=false
      - eureka.server.enable-self-preservation=false
    depends_on:
      - kafka
      - db1
