server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    host: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka-server:8761/eureka/